app:
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"
  cache:
    sync:
    enabled: true
    channel-prefix:
    channel: cache-invalidation
    compress-messages: false
    caffeine-ttl: 5m
    caffeine-max-size: 2000
    redis-ttl: 30m
